### ISSUE TITLE
"product_id" not working on a few methods

### ISSUE THREAD

**Issue by itaki** [danpaquin/gdax-python#286] opened 2018-04-11 01:23 UTC
"product_id" doesn't seem to be working on either the get_orders() or the cancel_all() methods. With get_orders, I can use the method, but not with a product_id. If I put a product_id in I get an error 

get_orders() got an unexpected keyword argument 'product_id'

However, with the cancel_all method, even leaving it blank I get this error "data=json.dumps({'product_id': product or self.product_id}), auth=self.auth)
AttributeError: 'AuthenticatedClient' object has no attribute 'product_id''

**Comment by itaki** [comment] 2018-04-11 03:15
Digging through the other issues I see the cancel_all problem may be related to the issue pointed out by bradowatson  a couple weeks ago where product="BTC-USD" but not product_id="BTC-ETH"

**Comment by mcardillo55** [comment] 2018-04-11 07:47
Dupe of #274. Closing.

**Closed by mcardillo55** 2018-04-11 07:47 UTC
Labels: documentation, duplicate

**Comment by itaki** [comment] 2018-04-12 17:55
Really don't think this is a direct duplicate of #274. If anything this information _extends_ the issues in #274. Nonetheless, I have added this info to it anyway.
