### ISSUE TITLE
OrderBook init failed

### ISSUE THREAD

**Issue by kingsfield** [danpaquin/gdax-python#99] opened 2017-07-25 13:43 UTC
```
Traceback (most recent call last):
  File "/Users/kingsfield/workspace/quant/spider/bitcoin/websocket_coinbase.py", line 37, in <module>
    order_book = gdax.OrderBook(product_id='BTC-USD')
  File "/usr/local/lib/python2.7/site-packages/gdax/order_book.py", line 20, in __init__
    self._client = PublicClient(product_id=product_id)
TypeError: __init__() got an unexpected keyword argument 'product_id'
```

**Comment by metachris** [comment] 2017-07-25 14:00
Duplicate of #98

**Comment by danpaquin** [comment] 2017-07-25 14:00
product_id has been removed from init and you must add it to every call. This is to ensure no mistakes are made when querying multiple products

**Closed by danpaquin** 2017-07-25 14:00 UTC

**Comment by Vacant0mens** [comment] 2017-11-16 00:14
I'm getting this error using the example in the `README.md`. Is that example outdated? What's the proper syntax for calling the OrderBook class?
