### ISSUE TITLE
Easy Fix** Cancel Orders function documention is wrong

### ISSUE THREAD

**Issue by bradowatson** [danpaquin/gdax-python#274] opened 2018-03-14 13:54 UTC
On the documentation page the function is listed as:
auth_client.cancel_all(product_id='BTC-USD')

But this generates an error:
TypeError: cancel_all() got an unexpected keyword argument 'product_id'

I looked at the code and the code is expecting "product" and not "product_id".

This works:
auth_client.cancel_all(product='BTC-USD')

So the fix is easy to either update the documentation or change the code slightly.

**Comment by itaki** [comment] 2018-04-11 20:42
Pretty sure this bug isn't just in documentation. I put another issue in that I think is related to this one, but since that one has been closed just add to this one.

Not only does 'product_id' not work, but 'product' doesn't work properly either. When used like this
auth_client.cancel_all(product='BTC-USD')
it cancels all orders in all products. When trying to use it for any of the other products like this
auth_client.cancel_all(product='ETH-USD')
it doesn't error, but also doesn't cancel any ETH-USD orders.

In the previous issue I posted I also mentioned that this problem seems to systemic in that 'product_id' also doesn't work for get_orders() either. 

I looked around in the code a bunch to try to figure out where exactly bradowatson was referring to it expecting "product" but am not sure exactly where that would be as the authenticated_client.py file looks right.

**Comment by mcardillo55** [comment] 2018-04-12 19:01
Hey @itaki,

After re-looking over both issues, I'm actually almost certain that both of these issues are old bugs that are fixed in the latest code on GitHub, but not yet uploaded to PyPi (so basically dupe of #208). So in other words, you should be using product_id, not product, in the latest code.

Could you try your code using the latest code and let me know?

Thanks.

**Comment by itaki** [comment] 2018-04-12 19:46
That definitely fixed all the problems. Thanks! Though there is an extra " on line 146 in the public_client which cause it to error. Will create a new issue.

**Comment by mcardillo55** [comment] 2018-04-17 01:51
Issue only exists because PyPi is out of date. Dupe of #208.

**Closed by mcardillo55** 2018-04-17 01:51 UTC
Labels: bug, documentation, duplicate
